/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IAccountLimitInterface extends Interface {
  getFunction(
    nameOrSignature: "activateAccount" | "getActivateAccount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivateAccount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivateAccount",
    data: BytesLike
  ): Result;
}

export interface IAccountLimit extends BaseContract {
  connect(runner?: ContractRunner | null): IAccountLimit;
  waitForDeployment(): Promise<this>;

  interface: IAccountLimitInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateAccount: TypedContractMethod<
    [owner: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getActivateAccount: TypedContractMethod<
    [owner: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateAccount"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getActivateAccount"
  ): TypedContractMethod<[owner: AddressLike], [boolean], "view">;

  filters: {};
}
