/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as axltbep20Sol from "./AXLTBEP20.sol";
export type { axltbep20Sol };
import type * as bep20 from "./BEP20";
export type { bep20 };
import type * as busdSol from "./BUSD.sol";
export type { busdSol };
import type * as testToken from "./TestToken";
export type { testToken };
export type { AccountLimit } from "./AccountLimit";
export type { DepositLimit } from "./DepositLimit";
export type { ExchangeRate } from "./ExchangeRate";
export type { HandleTransaction } from "./HandleTransaction";
export type { LiquidityPool } from "./LiquidityPool";
export type { ReferalProgram } from "./ReferalProgram";
